Repository bobertoyin/cubecrit, pull requests merged in 2024-05, with the labels that each got.

#24 21 create puzzles page
  cubecrit/controllers/puzzles.py
  cubecrit/models/puzzle.py
  cubecrit/sql/get_num_puzzles.sql
  cubecrit/sql/get_puzzle_page.sql
  cubecrit/templates/puzzles.html
Labels: enhancement

#17 simplify header styling, add dark theme toggle functionality
  cubecrit/static/js/init-theme.js
  cubecrit/static/js/set-theme.js
  cubecrit/static/styles/navbar.css
  cubecrit/templates/base.html
  cubecrit/templates/puzzle.html
Labels: enhancement

#16 Mock db connection for unit tests, improve code coverage and linting
  README.md
  cubecrit/controllers/index.py
  cubecrit/controllers/manufacturers.py
  cubecrit/controllers/puzzles.py
  cubecrit/models/manufacturer.py
  cubecrit/models/puzzle.py
  cubecrit/models/review.py
  cubecrit/sql/get_puzzle_page.sql
  cubecrit/templates/puzzles.html
  docker-compose.yml
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/models/test_manufacturer.py
  tests/models/test_puzzle.py
Labels: documentation

#34 add continuous integration workflow for Github Actions
  .github/workflows/ci.yml
Labels: enhancement

#33 Database sync functionality
  README.md
  cubecrit/__init__.py
  cubecrit/db.py
  cubecrit/sql/get_puzzle_page.sql
  cubecrit/sql/schema.sql
  cubecrit/sql/seed.sql
  cubecrit/sql/sync/countries.sql
  cubecrit/sql/sync/manufacturers.sql
  cubecrit/sql/sync/puzzle_types.sql
  cubecrit/sql/sync/puzzles.sql
  cubecrit/sync.py
  cubecrit/templates/puzzle.html
  cubecrit/templates/puzzles.html
  poetry.lock
  pyproject.toml
  tests/test_sync.py
Labels: bug, enhancement
